### ISSUE TITLE
Make links clickable

### ISSUE THREAD

**Issue by survivorbat** [center-key/pretty-print-json#14]
I believe it'd be a great addition for this library to automatically convert links in the json data to <a> tags so they can be clicked.

**Comment by dpilafian** [comment]
Implementation notes -- probably good to:
- Use a super simple regex, like `/"https?:\/\/.*[.].*"/` (no need to prove URL is strictly valid)
- Add an option to enable or disable, such as `makeLinks`, `aTags`, or `linksTags` -- https://github.com/center-key/pretty-print-json#options
