### ISSUE TITLE
Code cleanup, whitespace issues, introduce prettier?

### ISSUE THREAD

**Issue by Pustur** [center-key/pretty-print-json#23]
While contributing to this project I noticed that sometimes the whitespace is a bit all over the place. (closing brackets on the same level as the code inside them for example)

Would you be open to a PR that either:

- Introduces prettier to keep a consistent format throughout the codebase?
- Fixes the whitespace issues manually?

Let me know so I can work on this before you potenitally push a new version (so we do everything at once)

**Comment by dpilafian** [comment]
The concept of prettier is great, but the style choices result in code that is uglier than mud.  Prettier is really geared towards procedural programing and makes a mess of functional code.  Alignment is destroyed.  Clean, simple ternary assignments are expanded into bulky multiline blocks.  It assumes `if` statements will have multiline blocks.

Of course, some people like the style decisions of prettier, and the library is very upfront that it's opinionated.

The whitespace in **pretty-print-json** follows a very specific pattern.  Think of blocks of code indented like a hanging paragraph or like the JS equivalent of Python.  The advantage is that you can see where the block ends without analyzing the content of the code.  In the typical indentation used in most JS code you see, you cannot always tell if a line of code starts a new block with interpreting the code.

**Comment by Pustur** [comment]
Ok fair enough, I understand if you want to keep it this way.

The problem now however, is that the style you describe is not consistent throughout the codebase (my contributions have followed a different style for example). I would have gladly changed this if you mentioned it before merging my PRs.

If you still want me to fix the inconsistencies let me know, otherwise you can close this issue if you'd like to leave it like it is now 👍

**Comment by dpilafian** [comment]
If you want to put up another PR, go for it.

Sometimes the back-and-forth on PRs is too much effort compared to just updating the style next time I'm editing the code.  I submit a number of issues to give people an opportunity to contribute and learn about open source. I don't get too fussy about PRs since I just do it for fun.

**Comment by Pustur** [comment]
I just realized that some of the changes I was going to make were already taken care by you during a previous release, so there's not a lot to fix anymore.  
At this point I think you can change it yourself next time you touch the code.

Have a good night.
