### ISSUE TITLE
Switch to trailing comma style in spec/mocha.js

### ISSUE THREAD

**Issue by dpilafian** [center-key/pretty-print-json#26]
For **multiline** arrays and objects, the consistency of including a comma for the last item makes the code easier to edit and helps reduce merge diffs.

See:
https://jshint.com/docs/options/#trailingcomma

For example, change:
```javascript
const input = {
   '$':  'Money',
   '🚀': 'Unicode'  //no comma
   };
```
to:
```javascript
const input = {
   '$':  'Money',
   '🚀': 'Unicode',  //with comma
   };
```

**Comment by dpilafian** [comment]
I should have been more clear in the original description.  The trailing commas are to be applied to the coding style of the **spec/mocha.js** file itself.

For example, the `input` object on line 51 needs a trailing comma:
https://github.com/center-key/pretty-print-json/blob/master/spec/mocha.js#L51

Changing the output to include trailing commas would, unfortunately, break JSON.

> _"JSON, however, disallows trailing commas."_

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

**Comment by AlcidesA** [comment]
Oh right, I'm gonna fix that

**Comment by dpilafian** [comment]
PR #27 looks good.

By the way, the new fancy JSON5 supports trailing commas.  The future is getting brighter.
