### ISSUE TITLE
Add JSHint rule to disallow var declarations

### ISSUE THREAD

**Issue by dpilafian** [center-key/pretty-print-json#30]
Configure the project to enforce the JSHint rule that prohibits `var` statements.

See `"jshintConfig"` in **package.json**:
https://github.com/center-key/pretty-print-json/blob/master/package.json#L21

JSHint documentation:
https://jshint.com/docs/options/#varstmt

**Comment by guidimas** [comment]
Hello! I would like to help you with this for Hacktoberfest! May you assign it to me? Thank you.
