### ISSUE TITLE
Add color for null values

### ISSUE THREAD

**Issue by dpilafian** [center-key/pretty-print-json#4]
Style `null` values with the color `dimgray`.

Example JSON:
```
{ "x": null }
```

**Comment by dpilafian** [comment]
Similar to the `isBool` calculation, there needs to be an `isNull` calculation that sets `valSpan` to `'<span class=json-null>'` and the CSS needs to enhanced with `.json-null    { color: dimgray; }`.

**Comment by sowmiyamuthuraman** [comment]
@dpilafian working on it!
