### ISSUE TITLE
0.4.3 and 0.4.4 are broken for dynamic import

### ISSUE THREAD

**Issue by softwarecreations** [center-key/pretty-print-json#41]
I'm dynamically importing pretty-print-json.

On versions 0.4.3 and 0.4.4 the loaded object only has a default property, which is an empty object... and has no other properties in the root object or in default.
Whereas on 0.4.2 I get this, and it works.
![image](https://user-images.githubusercontent.com/28704571/106484528-5eaba780-64b8-11eb-8074-a5b0cd309be1.png)

**Comment by dpilafian** [comment]
Oops, sorry for breaking that.  The **pretty-print-json** module definition was changed to be a "named" export when the library was converted to TypeScript.

The standard `import` now should be done with curly braces:
```js
import { prettyPrintJson } from 'pretty-print-json';
```

For a dynamic `import`, the **Promise** will return a module to be used like:
```js
const url = '/libs/pretty-print-json.esm.js';
import(url).then(module => {
   const data = [3, 7, 21];
   const html = module.prettyPrintJson.toHtml(data);
   ...
   };
```

Here's a page to test out dynamically loading **pretty-print-json**:
https://pretty-print-json.js.org/dynamic/ 

<img width="686" alt="ES Module Dynamic Loading" src="https://user-images.githubusercontent.com/119555/106724886-9b14fb80-65bd-11eb-89b2-20817aa01d6e.png">

**Comment by softwarecreations** [comment]
Thanks bud, it's working great :)
