### ISSUE TITLE
Trouble with properly formatting array in JSON object

### ISSUE THREAD

**Issue by jcpage02** [center-key/pretty-print-json#57]
I have tried implementing this library correctly but the output I am seeing is not showing my array formatted the way I would like/expect.  I have also tried pasting my JSON into your online tool, but the format there is still not what I am needing.  The array in the "body" value is still a string.  Is there a way to have this library display this array as an array with proper line breaks and indentation? 

![image](https://user-images.githubusercontent.com/43834335/168857959-b06207c3-4ff3-4fe4-9d23-5bb245a985a9.png)

Output in my project:
![image](https://user-images.githubusercontent.com/43834335/168858808-e5e040af-0fc0-4887-82c5-b21d403e6954.png)

**Comment by jcpage02** [comment]
I have figure this out now.  I had to remove every instance of **\** and remove the **""** around the array.

**Comment by dpilafian** [comment]
The following JSON string looks correct:

`'{ "id": "f7617e30-3ed1-4076-81ed-ed4841bbff64", "body": [1001,1,"b9047b40-ab74-1f67-f3a6-e7048059906e","ok","machine is ok"] }'`

And it gets formatted as expected:

```js
{
   id: "f7617e30-3ed1-4076-81ed-ed4841bbff64",
   body: [
      1001,
      1,
      "b9047b40-ab74-1f67-f3a6-e7048059906e",
      "ok",
      "machine is ok"
   ]
}
```

As you have pointed out, the original `body` value is actually a string that can be converted to an array by unquoting it and removing the backslashes.  However, you almost definitely do not want to do this.

Something in your data processing is escaping the string to add in those backslashes when they shouldn't be there, or maybe you need to first pass the string to `JSON.parse()`.

```js
% node
> JSON.parse('["a", "b", "c"]');
[ 'a', 'b', 'c' ]
> JSON.parse('[\"a\", \"b\", \"c\"]');
[ 'a', 'b', 'c' ]
```

You'll avoid a lot of headaches if you make sure to always handle data the way it's intended at each step and never hack the format.
