### ISSUE TITLE
Key order not preserved

### ISSUE THREAD

**Issue by zliucd** [center-key/pretty-print-json#58]
I'm using ```pretty-print-json``` to print JSON data acquired from web server, but the order of keys displayed by ```pretty-print-json``` is not preserved - it prints keys in alphabetical descending order.

How to print json in original order? Thanks.

**Comment by dpilafian** [comment]
Please attach information to reproduce the bug, including version number and example input and output.

**Comment by zliucd** [comment]
It turned out the web server scrambled the order of JSON object.  Please
close this issue. Thanks!  BTW, is possible to collapse/expand the JSON
object in web page?

Dem Pilafian ***@***.***> 于2022年6月27日周一 11:39写道：
