### ISSUE TITLE
Pretty-print json in textareas ?

### ISSUE THREAD

**Issue by niels-hecquard** [center-key/pretty-print-json#9]
Hi,

I'm doing a tool a send json request and print the response.
For this I have 2 textareas where I'd like to pretty print the json typed.
As far as I understand, your tool pretty prints the json in pre tags, is it possible to your it to print in textareas ?

Thanks !

**Comment by Pustur** [comment]
I'm not the author, but if you only need the pretty spaces (without the colors) you can do it easily with `JSON.stringify`.  
Here's a demo: https://jsfiddle.net/h7gy9dsx/

**Comment by dpilafian** [comment]
You can certainly use a `<textarea>` element to display the JSON response, but `<textarea>` is generally used for getting user **input** not for displaying **output** (unless you want to also let the user edit the output).

What is rendered inside `<textarea>` is simple text (all the same color) not HTML.

Details:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

**Comment by niels-hecquard** [comment]
Thanks for your answers. Yes I needed to prettify the user's input live, not only the output. 
I found another tool which matches my needs ( [https://github.com/ajaxorg/ace] )
